#!/bin/bash

git_branch=$(git rev-parse --abbrev-ref HEAD)
tag_base="eu.gcr.io/tangy-orange/osmx"
previous_image=$(docker image inspect --format='{{.Id}}' "$tag:$git_branch" 2>/dev/null)

# Fail and exit immediately if any command doesn't succeed (e)
# or if any unbound variables lurk within (u)
set -eu

# Build the new image
docker build \
  --force-rm \
  --build-arg git_commit="$(git --no-pager show --no-patch --format='%H%n%s')" \
  --tag "$tag_base:$git_branch" \
  --file Dockerfile \
  $@ ./

# Remove the old version from local machine
if [ "$previous_image" != "" ]; then
  docker rmi $previous_image
fi

# Tag with commit id if staging/master
if [ "$git_branch" == "staging" -o "$git_branch" == "master" ]; then
  git_commit=$(git --no-pager show --no-patch --format='%H')
  docker tag "$tag_base:$git_branch" "$tag_base:$git_commit"
  echo "Tagged $tag_base:$git_commit"
fi
