version: 1
update_configs:
- package_manager: 'ruby:bundler'
  directory: '/'
  update_schedule: weekly
  commit_message:
    prefix: dependabot
  allowed_updates:
    - match:
        update_type: security
    - match:
        dependency_name: osm
